### ISSUE TITLE
Manipulate inventory

### ISSUE THREAD

**Issue by Emmanuel-Tsapekis** [marouen-lamiri/Second-Soul#64]
As a user, I want to manipulate the inventory, so I can select useful items

[SP: 5]
[Priority: 1]
[Risk: medium]

**Comment by Kishor0122** [comment]
Inventory looks good, items can be picked up, moved and equipped. Toggle on inventory works. Fighter and Sorcerer have different inventories as intended. Assuming item names and stats to come at a later time, signing off for now.
