### ISSUE TITLE
View inventory list

### ISSUE THREAD

**Issue by Emmanuel-Tsapekis** [marouen-lamiri/Second-Soul#65]
As a user, i want to be able to view my inventory list

[SP: 2]
[Priority: 3]
[Risk: low]

**Comment by Kishor0122** [comment]
Inventory looks good, items can be picked up, moved and equipped. Toggle on inventory works. Fighter and Sorcerer have different inventories as intended. Assuming item names and stats to come at a later time, signing off for now.
