### ISSUE TITLE
Upgrade Character Stats

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#74]
As a user, i want to be able improve my character’s stats according to my preferences and character class[SP: 13]
[Priority: 1]

**Comment by Emmanuel-Tsapekis** [comment]
###Task breakdown (in hours):

Discussing desired character stats and what they derive off (1h)
Discussing leveling system needed for stats (1h)
implementing level system, without stats (2h)
implementing desired stats in level system and appropriate classes (1h)
implementing stats to have an effect on gameplay:
  -armor / elemental resistances (1h)
  -attack power / spell power (1/2h)
  -(spell) critical strike chance (1h)
  - hit chance (1/2h)

**Comment by Emmanuel-Tsapekis** [comment]
### Demo Steps:
1- Start Game with default classes (berserker, mage)
2- show character stats in inspector
3- show combat
4- change stats manually
5- show difference in combat
6- restart game
7- choose different classes
8- show that stats differ from the last run with default classes

**Comment by Kishor0122** [comment]
Experience is gained when enemies are killed; when enough experience is accumulated the character automatically levels up. Stats are increased (based on the class) and health/energy is regenerated. Signing off.
