### ISSUE TITLE
Choose Fighter Class

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#75]
As a Fighter, i want to be able to choose the character’s class[SP: 1]
[Priority: 1]

**Comment by smileyWolf** [comment]
#### Black-Box Testing

Tests # | Inputs | Expected Output | Status
------------ | ------------- | ------------- | -------------
Stats differ based on Fighter's class| Choose class | The player's stats are different based on class chosen | Pass

**Comment by smileyWolf** [comment]
#### Demo Steps:
1. Left-Click on the terrain to move the Fighter (the default enabled character when game started.) 
2. Notice the Mini-Map moving in direction of the Fighter centered to the Mini-Map and the player icon rotates with the Fighter.
3. Press the 'e'-key.
4. Left-Click on the terrain to move the Sorcerer.
5. Notice the Mini-Map moving in direction of the Sorcerer centered to the Mini-Map and the player icon rotates with the Sorcerer.

**Comment by gfortin13** [comment]
![package diagram - character 1](https://cloud.githubusercontent.com/assets/3281015/5726156/409a7aca-9b27-11e4-9b4d-aec6bf84d9fd.png)

Slightly modified structure of character package, affects issues #76 #43

**Comment by gfortin13** [comment]
![package diagram - fighter classes](https://cloud.githubusercontent.com/assets/3281015/5726199/8b4e89c6-9b27-11e4-9504-25daa5405a31.png)

Extension on character diagram showing extra classes

**Comment by Kishor0122** [comment]
Choosing between the different fighter classes works. Signing off.
