### ISSUE TITLE
Choose Sorcerer Class

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#76]
[Priority: 1]
[SP: 1]
As a Sorcerer, i want to be able to choose the character’s class

**Comment by smileyWolf** [comment]
#### Demo Steps:
1. Left-Click on the button (from the Fighter's class on the left) interested to play with; notice the button like it is pressed.
2. Left-Click on the button (from the Sorcerer's class on the right) interested to play with; notice the button like it is pressed.
3. Press the Start-button.
 * Any Scene can be loaded when Start pressed.

**Comment by smileyWolf** [comment]
#### Demo Steps:
1. Left-Click on the button (from the Fighter's class on the left) interested to play with; notice the button like it is pressed.
2. Left-Click on the button (from the Sorcerer's class on the right) interested to play with; notice the button like it is pressed.
3. Press the Start-button.
 * Any Scene can be loaded when Start pressed.

**Comment by gfortin13** [comment]
![package diagram - sorcerer classes](https://cloud.githubusercontent.com/assets/3281015/5726220/a7c7e58e-9b27-11e4-924d-9ce3e8f3c39a.png)

Extension on character diagram showing extra classes

**Comment by Kishor0122** [comment]
Choosing between the different sorcerer classes works. Signing off.
