### ISSUE TITLE
Load Data

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#78]
[Priority: 2]
[SP: 3]
As a user, i want to be able to load my data

**Comment by smileyWolf** [comment]
#### Discussion ...
The US #78 is directly related to US #77

**Comment by marouen-lamiri** [comment]
All commits related to this story committed, also related to #77 :
- a0168db
- 4fcc2af
- f46a1a9
- a9764b9
- 2fa4867
- 0530cbf
- 0ccd565
-  fd6f3ac

**Comment by smileyWolf** [comment]
#### Black-Box Testing
Tests # | Inputs | Expected Output | Status
------------ | ------------- | ------------- | -------------
 |  |  | 
 |  |  | 
 |  |  | 
 |  |  | 
 |  |  | 
 |  |  | 
 |  |  |

**Comment by smileyWolf** [comment]
#### Demo Steps
1. 
2. 
3.

**Comment by smileyWolf** [comment]
#### ...

**Comment by Kishor0122** [comment]
Saved data (character stats, inventory items) is correctly loaded when game is re-started. Signing off.
