### ISSUE TITLE
Mini-Map

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#80]
As a user, i want to be able to view a mini-map on the HUD

[SP: 8]
[Priority: 2]

**Comment by Emmanuel-Tsapekis** [comment]
Final Rework of minimap @Kishor0122 :
![image](https://cloud.githubusercontent.com/assets/2415490/5619937/b1eb9364-94f4-11e4-9f25-459ed8a00810.png)
I believe the minimap is finalized and is circular, semi-transparent, has black lines to show dungeon walls, red dots for enemies, blue dots for allies, and a directional player icon to represent the rotation of the player him/herself.
Is there anything else you'd like to see in the minimap? Let us know

**Comment by Kishor0122** [comment]
Looks good! Has all the essentials for a mini-map. Things to consider for the future (not sure if these are already in place) would be to also show doors, cave/dungeon entrances etc. on the map. Also special enemies and bosses should have a different appearance (different colour/different size etc.). For now though it's good for me and I'm signing off on it.

**Comment by Emmanuel-Tsapekis** [comment]
#### New Task breakdown (for second version of the Minimap) (in hours):
- Research ways to accomplish the various needs of the Minimap:
	- Create lines dynamically to represent the map walls (0.5h)
	- Create Spheres dynamically to represent the characters' posiitons (1h)
	- Make objects (lines and spheres) appear in the Minimap, but not the main camera (1.5h)
	- Circular Minimap (3h)
	- Semi-transparent background (1h)
- Implementation
	- Create lines dynamically to represent the map walls (2h)
	- Create Spheres dynamically to represent the characters' posiitons (0.5h)
	- Make objects (lines and spheres) appear in the Minimap, but not the main camera (0.5h)
	- Circular Minimap (1h)
	- Semi-transparent background (1h)
	- Create directional player icon in Blender (2h)
	- Set up player icon to follow rotation of tracked player (0.5h)
