### ISSUE TITLE
Remove Player (Multiplayer)

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#81]
As a Fighter, i want to be able to remove a player

[SP: 2]
[Priority: 5]

**Comment by Kishor0122** [comment]
On the server (fighter) side, the client (sorcerer) can be removed from the game. When the sorcerer AI works, may want to consider removing the player but leaving the sorcerer, and having it revert to being controlled by the AI. Signing off.

**Comment by nico3865** [comment]
<b>Task Breakdown</b>

--add button and disconnect client onClick.

**Comment by nico3865** [comment]
#### Demo Steps
1. Open NetworkStartMenu scene in two game instances
2. Create a Fighter in one, and a Sorcerer in the other.
3. Click the "Remove Client" button next to the chat window.
4. Verify that the client (sorcerer) got disconnected, and that the server instance (fighter) can continue playing in one player mode.

**Comment by nico3865** [comment]
#### Blackbox Testing

- Click the "Remove Client" button next to the chat window.
- Verify that the client (sorcerer) got disconnected, and that the server instance (fighter) can continue playing in one player mode.
