### ISSUE TITLE
Enemies dropping Loot

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#82]
As a user, i want to be able to sometimes get items by defeating enemies.[SP: 8]
[Priority: 3]

**Comment by gfortin13** [comment]
commits originally linked issue #84, that was the wrong issue.

**Comment by gfortin13** [comment]
#### Task Breakdown (in hours)
- Discussing loot system with group (1h)
- Determine how to dynamically instantiate object type at run time (1h)
- Discuss how to implement loot selection with weights (1h)
- Implementation (1-2 days, further broken down)

**Comment by gfortin13** [comment]
#### Implementation Breakdown
- Setup new initial classes (Factory, item holder) (2h)
- Be able to pick up static item from group (2h)
- Dynamically drop random items at random drop rates (4h)

**Comment by gfortin13** [comment]
Enemies drop items at a 100% drop rate currently and all items have equal weights, easily adjust values to desired taste.

**Comment by gfortin13** [comment]
To add more natural feel item drops in random location of a 1 unit radius around the enemy.

**Comment by gfortin13** [comment]
#### Black-Box Testing

Tests  | Inputs | Expected Output | Status
------------ | ------------- | ------------- | -------------
Item drop | Kill an enemy | enemy drops a container with the random item | Pass
Item pick up | Click dropped item while in range | Item is added to inventory and is removed from game environment | Pass
Item pick up (while full) | Click dropped item while in range | Item remains in environment and inventory remains unchanged | Pass

**Comment by gfortin13** [comment]
![spawn items - diagram](https://cloud.githubusercontent.com/assets/3281015/5725770/00312d88-9b24-11e4-870c-3fbc91f75edb.png)

Diagram explaining loot process

**Comment by gfortin13** [comment]
#### Demo Steps
1. Open Inventory
2. Observe current items
3. Kill enemy
4. Click dropped item (capsule item holder)
5. Open Inventory
6. Observe new picked up item

**Comment by Kishor0122** [comment]
Enemies correctly drop loot, which can be picked up by the player on click. Item appears in the inventory correctly. In the future, item name should appear on mouse-over before picking up. Signing off.
