### ISSUE TITLE
Start Menu

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#83]
As a user, i want to have a main screen[SP: 1]
[Priority: 2]

**Comment by Kishor0122** [comment]
Signing off.

**Comment by smileyWolf** [comment]
#### The Start Screen

The Start Screen US is a combination of the  Choose Fighter Class US, Choose Sorcerer Class #76, and Networking US.
Below is a final look of the Start Screen Scene.

![startscreen](https://cloud.githubusercontent.com/assets/2501915/7216594/c07fd668-e5d2-11e4-8899-93da435d3e68.png)
