### ISSUE TITLE
HUD for playable Characters

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#85]
[Priority: 1]
[SP: 13]
As a user, i want a HUD for my characters (Fighter and Sorcerer).

**Comment by smileyWolf** [comment]
#### First Draft

**Comment by smileyWolf** [comment]
#### Task breakdown (in hours)
*

**Comment by smileyWolf** [comment]
#### Implementation Breakdown (in hours)
*

**Comment by smileyWolf** [comment]
#### Demo Steps
1.

**Comment by smileyWolf** [comment]
#### Black-Box Testing

Tests # | Inputs | Expected Output | Status
------------ | ------------- | ------------- | -------------
 |  |  |

**Comment by gfortin13** [comment]
![action - menu bar - template](https://cloud.githubusercontent.com/assets/3281015/5889225/b4904d8a-a3ea-11e4-82a9-5731fed94415.png)

Action bar template

**Comment by gfortin13** [comment]
![skill tab - template](https://cloud.githubusercontent.com/assets/3281015/5889227/bbf9e5ae-a3ea-11e4-995e-b944906427c1.png)

Skill tab template

**Comment by smileyWolf** [comment]
#### ...

**Comment by gfortin13** [comment]
![domain diagram - skill node](https://cloud.githubusercontent.com/assets/3281015/6142621/c5d8e0a2-b187-11e4-97ae-2b2a347c6fc4.png)

Simple data structure used for holding skills on HUD, variables excluded

**Comment by Kishor0122** [comment]
Skill-tab opens correctly, unlocking and assigning skills works. Need tool-tips again for the skills, also maybe a way of indicating that ctrl+number is how you assign a skill. Also feel like there should be more of an animation when you click on a skill to unlock it. Signing off.

**Comment by gfortin13** [comment]
Note: This story encountered a lot of bumps along development due to dynamic instantiation of some features, needing some restructuring and refactoring to accommodate the requirements. This required the story to be reevaluated and pushed back to a further iteration to be completed.
