### ISSUE TITLE
Skills and Spells for characters

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#86]
[Priority: 1]
[SP: 13]
As a user, i want my characters to be able to use skills and spells during combat (around 5 skills and 5 spells)

**Comment by marouen-lamiri** [comment]
##### Task Breakdown:
1- Research possible assets to use as spells and skills.
2- Create a skill and spell repertoire to what is available to the player depending on his class
3- Create skills and spells

#### Implementation Breakdown:
1- Create Projectile behavior script for projectile spells
2- Create all-projectile related spells
3- Create basic skills (such as charge, focus...)
4- Create Area behavior script for spells affecting a certain area
5- Create spells that affect an area

**Comment by marouen-lamiri** [comment]
#### Black-Box Testing

Tests # | Inputs | Expected Output | Status|
------------ | ------------- | ------------- | -------------|
|Player casting a projectile type spell|||
|Player casting a area type spell|||
|Player using a skill|||
|Player using a class specific skill||| 
|Player using a class specific spell|||

**Comment by marouen-lamiri** [comment]
#### Demo Steps:
1- Select Spell or Skill to use
2- Use the appropriate key to use the Spell or Skill
3- If used on an enemy, Hover over the health bar and Marvel at the damage the enemy has sustained

**Comment by marouen-lamiri** [comment]
PS: No Demo steps needed since no user input is necessary to see the actions of the AI

**Comment by Kishor0122** [comment]
Skills work on both fighter and sorcerer. Perhaps need to tone down the animations on some of the sorcerer skills (e.g. the cyclone), as well as on the fighter attack buff. Also need tool-tips for the skills. Signing off.
