### ISSUE TITLE
Sorcerer AI

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#87]
[Priority: 1]
[SP: 20]
As a user, i want a companion AI for the sorcerer soul in single player

**Comment by marouen-lamiri** [comment]
##### Task breakdown:
1- Research how AI is implemented in related video (2h)
2- Discuss how AI should be presented to the User, should he be able to control his AI? if so, what degree of freedom should we give him (2h) 
3- Research any potential external libraries that may enable us to optimize the AI development. (Decision Trees...) (2h)
4- Implementation (Further breakdown to be added)

#####  Implementation Breakdown
1- N/A

**Comment by marouen-lamiri** [comment]
#### Black-Box Testing

| Tests # | Inputs | Expected Output | Status |
| :-: | :-: | :-: | :-: |
| 1: Sorcerer next to you | None | Comes next to you | Pass |
| 2: Casts spells on enemies | None | Spell cast | Pass |
| 3: Detect Nearest Enemy to the player | None | Detects the enemy | Pass |

#### Regression Testing:

These issues have been retested: #44 #86 #92 #91 #43 #76 #68 #44 #63 #29
Tests failed: None
Last edit: 07/04/2015

Demo step:
Step 1: Walk around (Sorcerer will follow your character)
Step 2: Get near enemies (Sorcerer will attack the nearest one)

**Comment by Kishor0122** [comment]
Sorcerer AI works. Will follow the player around, detect and cast spells on enemies. Perhaps need to somehow limit the sorcerer from using all of the joint mana pool. Signing off.
