### ISSUE TITLE
In-Game Main Menu

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#88]
As a user, i want to have an in-game main menu[SP: 3]
[Priority: 3]

**Comment by smileyWolf** [comment]
#### First Draft
Here is the first prototype of our in-game main menu.

![ingamemenu](https://cloud.githubusercontent.com/assets/2501915/6223086/645d05fa-b62e-11e4-9908-05b1152892ec.png)

**Comment by smileyWolf** [comment]
#### Task breakdown (in hours)
* Discuss the component and visual-part of the User Story.* (1h)
* Research different types of In-Game menus.* (1h)
* Implementation (further broken down) (1 day)

**Comment by smileyWolf** [comment]
#### First Draft
Here is the first prototype of our in-game main menu.

![ingamemenu](https://cloud.githubusercontent.com/assets/2501915/6223086/645d05fa-b62e-11e4-9908-05b1152892ec.png)

**Comment by smileyWolf** [comment]
#### First prototype implementation

Here is the first version of the in-game menu.

![ingamemenu-2](https://cloud.githubusercontent.com/assets/2501915/6236908/6dbdf986-b6bc-11e4-92f6-530297c970b5.png)

**Comment by smileyWolf** [comment]
#### New (final) version

Below is the new (final) version of the in-game menu, yet not linked to the game-scene. (5f7a83d)
The Box's height is adjusted depending on the number of buttons included in the code.

![ingamemenu-3](https://cloud.githubusercontent.com/assets/2501915/6321485/4ee7fb92-bacc-11e4-9824-7b06be574ae5.png)

**Comment by smileyWolf** [comment]
#### Demo Steps
1. L

**Comment by smileyWolf** [comment]
#### Black-Box Testing

Tests # | Inputs | Expected Output | Status
------------ | ------------- | ------------- | -------------
Follow Fighter | Left-Click in any location on the terrain. | The Mini-Map's projected picture changes related to the Fighter's position centered on the map. | Pass

**Comment by smileyWolf** [comment]
#### Demo Steps
1. L

**Comment by smileyWolf** [comment]
#### In-Game Menu linked to the game

Here is how the menu looks within the game.

![ingamemenu-4](https://cloud.githubusercontent.com/assets/2501915/6321925/eff885a6-bad6-11e4-8145-46df59e4b32a.png)

**Comment by smileyWolf** [comment]
#### First Draft (Stats)

Here is the first prototype of our new Player's stats display.

![displayplayerstats-2](https://cloud.githubusercontent.com/assets/2501915/6322417/1e1a1fe8-bae2-11e4-8b00-dc49813456ee.png)

**Comment by smileyWolf** [comment]
1

**Comment by smileyWolf** [comment]
2

**Comment by smileyWolf** [comment]
3

**Comment by smileyWolf** [comment]
4

**Comment by smileyWolf** [comment]
5

**Comment by Kishor0122** [comment]
Menu correctly opens on escape key, and stats page correctly opens on 's' key. Love the appearance. Mouse-over shows tool-tip which is nice. One comment, when you close the stats menu the details section should collapse, i.e. if you open the stats again the details section should not be open. Signing off.

**Comment by smileyWolf** [comment]
#### Fix to the Stakeholder's comment

Fixed

**Comment by smileyWolf** [comment]
#### Fix the Update-issue

Put the stats' updates into the right place - the Update method; commit (https://github.com/marouen-lamiri/Second-Soul/commit/6b1a2f063c8d7b3790affecbe067eb8f97075ee0).

**Comment by marouen-lamiri** [comment]
#### Bug tracking:
-Fix key duplication issue

**Comment by Emmanuel-Tsapekis** [comment]
Dan, theres a key duplication error. You're adding to the menu each update. You want to only add in start and update in update menu

**Comment by smileyWolf** [comment]
#### Fixed the Duplicate Bug

Here is the commit that fixes the duplicate bug (https://github.com/marouen-lamiri/Second-Soul/commit/627fafa45095479ee93a956b5aa0196d5aa19eab).

**Comment by smileyWolf** [comment]
#### Fixing the Click-While-Opened-Menu/Stats issue

Here are the commits that fixed the bug referred to Click-While-Opened-Menu/Stats (https://github.com/marouen-lamiri/Second-Soul/commit/5d4e089b1e0067c013f766ef4a13d1b145c4af54) and (https://github.com/marouen-lamiri/Second-Soul/commit/752981a5246fc20045eaf217787b7a7bea226ed6).

**Comment by smileyWolf** [comment]
#### New Regression Testing

These issues have been retested: #27, #74, #90, #83
Tests failed: None
Last edit: 08/04/2015
