### ISSUE TITLE
Enemies wandering in groups or by themselves

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#89]
[Priority: 2]
[SP: 13]
As a user, i want to see my enemies wandering in groups or by themselves

**Comment by Emmanuel-Tsapekis** [comment]
##### Task breakdown:
1- Research proper movement methods for videogame development (3h)
2- Discuss how enemies should be grouped up (0.5h) 
3- Discuss how enemies should wander(0.5h)
4- Implementation (Below)

#####  Implementation Breakdown
1- Refactor character movement system such that supports different influences (Using acceleration ->velocity - >position) (3h)
2- Add method in "EnemyFactory.cs" to allow spawning enemies in groups (1h)
3- Make enemies exhibit "separation" such that they dont stick too close together (1.5h)
4- Have enemies wander within a certain radius (0.5h)

**Comment by Emmanuel-Tsapekis** [comment]
#### Black-Box Testing

| Tests #       | Inputs          | Expected Output| Status |
| :-------------: |:-------------:| :-----:| :-----:|
| 1: Enemies spawn in groups | None | Enemies are grouped up by default |  Pass |
| 2: Enemies wander |None | Enemies wander if not aware of the player| Pass |
| 3: Enemies still can notice player | Move player within aware radius of and enemy | Enemy chases player | Pass |
| 4: Enemies spawn within the confines of the map |None | Enemies are not standing outside of the map by default| Fail |

#### Black-Box Testing
1- Start game
2- Go into a scene with enemies
3- Observe the state of enemies
4- Make an enemy, or a group of enemies aware of you
5- Observe that their reaction is proper

**Comment by Kishor0122** [comment]
Individual enemies wander around, and groups of enemies wander together. Signing off.
