### ISSUE TITLE
Create a Town

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#90]
As a user, i want to have access to a town in the game[SP: 3]
[Priority: 5]

**Comment by marouen-lamiri** [comment]
#### Task Breakdown & Implementation breakdown:
- Built Town (Graphical, no code related work) (3.5h)
- Link Town to be built to the Start scene and Dungeon Scene (0.25h)

#### Black-Box Testing:
|Tests # | Inputs | Expected Output | Status|
|------------ | ------------- | ------------- | -------------|
| Start Game | Select Game-Play mode | Find yourselves in a Town | Pass |
| Go to dungeon | Press "Tab" or go to the highlighted area | Find yourselves in a Dungeon & Forest | Pass |

#### Integration Testing:
|Tests # | Inputs| Related Story | Expected Output | Status|
|------------ | ------------- | ------------- |  ------------- | -------------|
| No Game-Objects Lost while transitioning | N/A | #12 #43 #44| No Game-Objects lost in transition  | Pass |

#### Demo Steps:
1 - Start Game-play
2 - Go to the highlighted area or press "Tab"

**Comment by Kishor0122** [comment]
Game starts in the town. Can move in and out of the town. Signing off.
