### ISSUE TITLE
Chatting System

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#91]
As a user, i want to have the ability to chat when in multiplayer[SP: 8]
[Priority: 2]

**Comment by Kishor0122** [comment]
Chat works. Signing off.

**Comment by nico3865** [comment]
#### Demo Steps
1. Open NetworkStartMenu scene in two game instances
2. Create a Fighter in one, and a Sorcerer in the other.
3. Press the Return key --> Verify it opens the chat box
4. Focus the chat textbox, write a message and press Return --> Verify that the message appears in the textarea, in both game instances (server and client)
5. Unfocus the chat and wait 6 seconds  --> Verify that the chat buttons and textbox disappear, only the textarea remains visible.

**Comment by nico3865** [comment]
#### Task Breakdown (actual):

(1h) create textbox and send button and send text
(0.5h) make chat disappear after 6 seconds 
(2h) make all values relative and settable as class variables.
(1h) move chat window to bottom left.

**Comment by nico3865** [comment]
#### Black Box Testing

| Tests # | Inputs | Expected Output | Status |
| --- | --- | --- | --- |
| Connect | Open NetworkStartMenu scene in two game instances. Create a Fighter in one, and a Sorcerer in the other | Verify game can be played as usual | Pass |
| Open Chat | Press the Return key | --> Verify it opens the chat box | Pass |
| Send message | Focus the chat textbox, write a message and press Return | --> Verify that the message appears in the textarea, in both game instances (server and client) | Pass |
| Inactive Chat Disappears | Unfocus the chat and wait 6 seconds | --> Verify that the chat buttons and textbox disappear, only the textarea remains visible | Pass |

These issues have been retested: #73
Tests failed: None
Last edit: 08/04/2015
