### ISSUE TITLE
Master-Server

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#92]
[Priority: 3]
[SP: 5]
As a user, i want to have access to the server even in a location like Concordia (firewalls)

**Comment by nico3865** [comment]
#### Demo Steps
1. Open NetworkStartMenu scene in two game instances, on two different computer both connected to the internet.
2. Click Connect as Server in one, Connect as Client in the other (and select a Room).
3. Test every pre-existing story: game play shouldn't change

**Comment by nico3865** [comment]
#### Task Breakdown (actual):

(2h) research how to use Unity's master server web service.
(1h) create some test buttons using master server connection logic 
(1h) create a list of rooms, obtained after connecting to Unity's master server.
(0.25) set old buttons to use the new master server logic

**Comment by nico3865** [comment]
#### Black Box Testing
1. Open NetworkStartMenu scene in two game instances, on two different computer both connected to the internet.
2. Click Connect as Server in one, Connect as Client in the other (and select a Room).
3. Test every pre-existing story: gameplay shouldn't change.

These issues have been retested: #87, #73, #91, #78, #77, #64, #45 
Tests failed: None
Last edit: 09/04/2015
