### ISSUE TITLE
Treasure Chest

### ISSUE THREAD

**Issue by marouen-lamiri** [marouen-lamiri/Second-Soul#93]
As a user, i want to be able to find treasure chests in the map and retrieve an item from it[SP: 5]
[Priority: 1]

**Comment by gfortin13** [comment]
#### Task breakdown (in hours)
- Discuss treasure chest functionality and location (0.5h)
- Find a Chest asset (1h)
- Creation of Chest prefab and object (2h)

**Comment by gfortin13** [comment]
#### Black-Box Testing

Tests # | Inputs | Expected Output | Status
------------ | ------------- | ------------- | -------------
Get in range | Click the chest | Character walks to chest | Pass
Open Chest | Click the chest while in range | Chest opens and drops items | Pass

**Comment by gfortin13** [comment]
#### Demo Steps
1. Add a Chest close to the Player
2. Walk to the Chest
3. Click to open the Chest
4. Pick up dropped items from the chest

*Note: since in normal game play Treasure chests should be random and rare spawns, we statically add one to show behavior for demo prupose

**Comment by gfortin13** [comment]
![treasure chest interaction - diagram](https://cloud.githubusercontent.com/assets/3281015/6478886/dcaa3992-c209-11e4-82d6-95d51281bcbb.png)

Interaction with Player, Treasure Chest and related objects

**Comment by Kishor0122** [comment]
Treasure chest opens on click and drops items, which can be picked up. An opening animation would be a good thing to add. Signing off.
