### ISSUE TITLE
Storage stash for player

### ISSUE THREAD

**Issue by Emmanuel-Tsapekis** [marouen-lamiri/Second-Soul#95]
[Priority: 3]
[SP: 13]
As a user, I would like to have a storage to stash items away in.

**Comment by gfortin13** [comment]
#### Task Breakdown (in hours)
- Discussing stash functionality (1h)
- Creation of Art used (1h)
- Align and display stash (2h)
- Implementation (further broken down) (1 days)

**Comment by gfortin13** [comment]
#### Implementation Breakdown
- Refactoring of methods for common use between storage objects (3h)
- Add similar methods as issues #64 #65 for manipulating items and transferring from one storage to another (3h)

**Comment by gfortin13** [comment]
#### Black box testing

| Tests #       | Inputs          | Expected Output| Status |
| :-------------: |:-------------:| :-----:| :-----:|
| 1: Display Stash | Press 'u' | stash displayed |  Pass |
| 2: Move Item | Click on item and then click on the new location |   Item moved| Pass |
| 3: Close stash| Press 'u' when inventory displayed |  stash closed | Pass |
| 4: Drag Transfer| Drag item from inventory to stash | Item transferred location | Pass |
| 5: Click Transfer| Right click an item in inventory |  Item goes to first available stash position | Pass |
| 6: Drag Transfer 2| Same as 4) but from stash to inventory |  Item transferred location | Pass |
| 7: Click Transfer 2| Same as 5) but from stash to inventory |  Item goes to first available inventory position | Pass |

**Comment by gfortin13** [comment]
#### Demo Steps
1. Open stash and inventory
2. Move items back and forth via click or drag
3. Close stash and inventory
