### ISSUE TITLE
Different monsters

### ISSUE THREAD

**Issue by Emmanuel-Tsapekis** [marouen-lamiri/Second-Soul#96]
As a user, I would like to encounter different kinds of enemies[SP: 20]
[Priority: 1]

**Comment by Emmanuel-Tsapekis** [comment]
##### Task breakdown:
1- Discuss what different enemies should be included(1h)
2- Discuss how each enemy should differ from the original skeletal warriors(2h)
3- Acquire animated 3D assets to use for enemies (4h)
3- Implementation (Below)

#####  Implementation Breakdown
1- Create state machines to animate each model (2h)
2- Implement Golem(1h)
3- Implement Imp (2.5h)

**Comment by Emmanuel-Tsapekis** [comment]
#### Black-Box Testing

| Tests #       | Inputs          | Expected Output| Status |
| :-------------: |:-------------:| :-----:| :-----:|
| 1: Golems don't wander, and instead "sleep" | None | Golems "sleep" |  Pass |
| 2: Golems don't start moving until they completely "wake up" | Gain attention of a Golem | Golems don't start moving until the wakeup animation is complete|  Pass |
| 3: Imps have a longer range, and throw fireballs instead of basic attacks |Gain attention of an Imp | Imps throw fireballs at the Fighter| Pass |

#### Demo Steps
1- Start game
2- Go into a scene with enemies
3- Observe the state of a Golem without your attention
4- Gain attention of a Golem
5- Gain attention of an Imp

**Comment by Kishor0122** [comment]
Skeleton, Imp and Golem all work. Golem has a non-agro state and a agro-state which are different. Very cool golem btw. Signing off.

**Comment by Emmanuel-Tsapekis** [comment]
#### Enemies Chosen
Golem:
![image](https://cloud.githubusercontent.com/assets/2415490/7039856/2b2c7606-dd95-11e4-995c-613d5a4946ee.png)

Imp:
![image](https://cloud.githubusercontent.com/assets/2415490/7040134/5d2b09fc-dd99-11e4-8143-bd799af0b351.png)
