### ISSUE TITLE
Town Shop

### ISSUE THREAD

**Issue by Emmanuel-Tsapekis** [marouen-lamiri/Second-Soul#97]
[Priority: 2]
[SP: 13]
As a user, I would like to have a shop at the town to acquire new items

**Comment by marouen-lamiri** [comment]
GUI prototype on how the shop is going to look

![capture](https://cloud.githubusercontent.com/assets/3285946/6648197/622334de-c9ad-11e4-9d5a-fbaba8dcd8f4.PNG)

**Comment by marouen-lamiri** [comment]
#### Task Breakdown
1- Prototype the shop
2- Discuss how items should be added to the inventory
3- Discuss possible Curreny Systems

#### Implementation Breakdown
1- Create buttons linking to each type of item, with description and image
2- Add Items to inventory
3- Add Currency system for each Type of currency (Fighter -> Gold, Sorcerer-> Soul Shard)
4- Make each type of Shop have different Items related to the player itself
5- Add currency retrieval when Killing an opponent
6- Use currency to buy (or be told that you cannot buy it)

**Comment by marouen-lamiri** [comment]
#### Black-Box Testing

| Tests #       | Inputs          | Expected Output| Status |
| :-------------: |:-------------:| :-----:| :-----:|
| 1: Open Shop | Press on shop sign | Shop window opens |  Pass |
| 2: Character doesn't move when shop UI is pressed|press on shop window| player doesn't move| Fail |
| 3: Press item to show description and buying option|  Press item button| Description and buying buttons appear | Pass |
| 4: Buy Item| Press on Buy button | Item added to inventory |  Pass |
| 5: Sell Item | Press on Sell button | Pass |
| 6: Sell Item not in inventory |  Press sell button| error message displayed | Pass |
| 7: Buy Item with no space in inventory | Press on Buy button | Error message displayed |  Pass |
| 8: Display appropriate Item list depending on player | Press on shop sign | Correct shop opens | Pass |
| 9: Get currency when selling item | Press sell button | Money added in the inventory | Pass |
| 10: Spend currency when selling item | Press Buy button | Money removed in the inventory | Pass |
| 11: Retrieve Currency when defeating an enemy | Kill enemy | Money added in the inventory | Pass |
| 12: Display Currency in inventory | open inventory | Amount of money displayed in the inventory | Pass |
| 13: Display Appropriate Currency in inventory | open inventory | Amount of money displayed in the inventory with appropriate logo (Gold for fighter, Purple eye for Sorcerer) | Pass |

#### Demo Steps:

#### Regression Testing:
These issues have been retested:
Tests failed: None
Last edit: 16/03/2015

**Comment by smileyWolf** [comment]
#### Demo Steps:

1. Press on shop sign to open window
2. Select one of the 3 options: Buy, Sell or close
3. Press on Item, item description will show up
4. Press on Buy/Sell button (depending on your choice in step 2), the appropriate action will occur
5. Press close to close shop
